import type { Metadata } from "next";
import "./globals.css";
import { Setup } from "@/components/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/Sidebar";
import { TopBar } from "@/components/TopBar";
import { ThemeProvider } from "@/components/ThemeProvider"
import Provider from "@/redux/provider"
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased bg-background text-foreground">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Provider>
          <Setup />
          <div className="flex min-h-screen">
            <Sidebar />
            <div className="flex-1 flex flex-col">
              <TopBar />
              <main className="flex-1 p-4 md:p-8 bg-background">{children}</main>
            </div>
          </div>
          </Provider>
        </ThemeProvider>      
      </body>
    </html>
  );
}
