# Generated by Django 5.2.1 on 2025-05-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
